# Generated by Django 5.0.1 on 2024-01-22 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_photo_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='article',
        ),
        migrations.RemoveField(
            model_name='file',
            name='article',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file',
        ),
        migrations.AddField(
            model_name='article',
            name='uploaded_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_content',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='file_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='file',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
